---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: install requirements
    become: yes
    apt:
      name: ["software-properties-common"]
      state: latest
      update_cache: yes

  - name: "install python3.6 and pip"
    become: yes
    apt:
      name: ["python3.6", "python3-pip", "python-pip"]
      state: latest
      update_cache: yes

  - name: update pip
    become: true
    shell: |
      sudo -H pip3 install --upgrade pip
  
  - name: Install bottle python package
    become: true
    pip:
      name: fastapi, uvicorn, sqlalchemy
