---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: "install python and pip"
    become: yes
    apt:
      name: ["python3", "python3-pip"]
      state: latest
      update_cache: yes

  - name: install pip dependencies
    become: true
    shell: |
      pip3 install fastapi
      pip3 install "uvicorn[standard]"
