---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: install requirements
    become: yes
    apt:
      name: ["software-properties-common"]
      state: latest
      update_cache: yes

  - name: "install python and pip"
    become: yes
    apt:
      name: ["python3.8", "python-pip"]
      state: latest
      update_cache: yes

  - name: install pip dependencies
    become: true
    shell: |
      pip install fastapi
      pip install "uvicorn[standard]"
