---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: remove dependencies that are no longer required
    become: yes
    apt:
      autoremove: yes

  - name: "install dependencies"
    become: yes
    apt:
      name: ["python3", "pip"]
      state: latest
      update_cache: yes

  - name: start server
    become: true
    shell: |
      pip install fastapi
      pip install "uvicorn[standard]"
