---
- name: copy dist backend folder to ec2 server
  become: yes
  copy:
    src: ~/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    uvicorn main:app --reload