version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow-short-id:
        type: string
        default: ${CIRCLE_WORKFLOW_ID:0:7}
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo << parameters.workflow-short-id >>
            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow-short-id >>

jobs:
  build-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  build-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  test-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  scan-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  test-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  scan-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend smoke test
          command: |
            echo 0
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople \
              --region=us-east-1 \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment:
          workflow-short-id: "${CIRCLE_WORKFLOW_ID:0:7}"
  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: ls 
          command: |
            ls -la
      - run:
          name: copy local files to s3
          command: |
            aws s3 cp ~/index.html s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}/ --recursive
      - destroy-environment:
          workflow-short-id: "${CIRCLE_WORKFLOW_ID:0:7}"


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend 
      - test-frontend:
          requires: [build-frontend]
      - scan-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - deploy-infrastructure:
          requires: [test-frontend,scan-frontend,test-backend,scan-backend]
      - deploy-frontend:
          requires: [deploy-infrastructure]
      
